### PR TITLE
Update ai.js

### PR DESCRIPTION
**Pull request by pandrax**
moar functions! and variables!

### CODE REVIEW

**Review by greydoubt — COMMENTED** [review]
1 change

**Review by greydoubt — COMMENTED** [review]
2nd change: more vars

**Comment by pandrax** [comment]
ack

**Review by greydoubt — CHANGES_REQUESTED** [review]
add a place-holder //

**Comment by pandrax** [comment]
ack

**Review by pandrax — COMMENTED** [review]
ack

**Comment by greydoubt** [comment]
sync / error w rebase

**Review by greydoubt — APPROVED** [review]

**Comment by greydoubt** [comment]
sync

**Pull request merged**
